export const GET_CONTINENT_BY_CODE = 'GET_CONTINENT_BY_CODE';
export const GET_CONTINENT_BY_CODE_SUCCESS = 'GET_CONTINENT_BY_CODE_SUCCESS';
export const GET_CONTINENT_BY_CODE_ERROR = 'GET_CONTINENT_BY_CODE_ERROR';
